apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      # Add toleration for the CriticalAddonsOnly taint
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: auth-postgres
          image: postgres:13-alpine
          env:
            - name: POSTGRES_DB
              value: auth_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432

          # Add resource requests/limits for better scheduling
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-postgres-storage

      volumes:
        - name: auth-postgres-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres
spec:
  selector:
    app: auth-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432