apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-pvc-v2
  labels:
    app: auth-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi