apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-cluster-binding
subjects:
  - kind: User
    name: system:node:EKSGetTokenAuth  # Matches the user in your output
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit  # Using built-in edit cluster role
  apiGroup: rbac.authorization.k8s.io