apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::080927831740:role/chat-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-deployment-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-deployment-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: github-actions-sa
    namespace: default
roleRef:
  kind: Role
  name: github-actions-deployment-role
  apiGroup: rbac.authorization.k8s.io