---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: github-actions-role
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/status"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-binding
  namespace: default
subjects:
  - kind: User
    name: github-actions
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io