apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-redis
  template:
    metadata:
      labels:
        app: auth-redis
    spec:
      containers:
        - name: auth-redis
          image: redis:7-alpine
          env:
            - name: REDIS_PASSWORD
              value: "password"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: auth-redis-storage
      volumes:
        - name: auth-redis-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis
spec:
  selector:
    app: auth-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379