---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine  # or `redis:6-alpine` for stability
          env:
            - name: REDIS_PASSWORD  # (Optional) If password is enabled
              value: "password"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-storage
      volumes:
        - name: redis-storage
          emptyDir: {}  # For development (not persistent)

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service  # Matches `SPRING_REDIS_HOST` in ConfigMap
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379      # Service port
      targetPort: 6379 # Redis container port