name: Deploy Auth PostgreSQL to EKS

on:
  push:
    branches: ["*"]
    paths:
      - 'services/auth-service/k8s/postgres-deployment.yml'
      - 'services/auth-service/k8s/postgres-pvc.yml'
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    name: Deploy Auth PostgreSQL
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure EKS cluster access
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          kubectl cluster-info
          kubectl auth whoami

      - name: Check existing resources
        run: |
          echo "=== Current PVCs ==="
          kubectl get pvc --all-namespaces || true
          
          echo "=== Storage Classes ==="
          kubectl get storageclass || true

      - name: Clean up previous failed deployment
        run: |
          kubectl delete deployment auth-postgres --ignore-not-found=true --timeout=60s || true
          kubectl delete pvc auth-postgres-pvc --ignore-not-found=true --timeout=60s || true
          sleep 10

      - name: Deploy PostgreSQL PVC
        run: |
          kubectl apply -f services/auth-service/k8s/postgres-pvc.yml 
          # Wait for PVC to be bound
          timeout 60 kubectl wait --for=condition=bound pvc/auth-postgres-pvc || echo "PVC not bound yet"

      - name: Deploy PostgreSQL Deployment
        run: |
          kubectl apply -f services/auth-service/k8s/postgres-deployment.yml --server-side

      - name: Wait for rollout with debugging
        run: |
          timeout 300 kubectl rollout status deployment/auth-postgres || {
            echo "Rollout failed, investigating..."
          
            echo "=== Pod Status ==="
            kubectl get pods -l app=auth-postgres -o wide
          
            echo "=== Pod Details ==="
            for pod in $(kubectl get pods -l app=auth-postgres -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo ""); do
              echo "--- Describing pod $pod ---"
              kubectl describe pod $pod
              echo "--- Logs for $pod ---"
              kubectl logs $pod --previous || kubectl logs $pod || echo "No logs available"
            done
          
            echo "=== PVC Status ==="
            kubectl describe pvc auth-postgres-pvc
          
            echo "=== Events ==="
            kubectl get events --field-selector involvedObject.name=auth-postgres --sort-by=.metadata.creationTimestamp
          
            exit 1
          }

      - name: Verify deployment success
        run: |
          echo "=== Final Deployment Status ==="
          kubectl get deployment auth-postgres -o wide
          
          echo "=== Final Pod Status ==="
          kubectl get pods -l app=auth-postgres -o wide
          
          echo "=== Service Status ==="
          kubectl get svc -l app=auth-postgres
          
          echo "=== PVC Status ==="
          kubectl get pvc auth-postgres-pvc