name: Debug AWS Credentials

on:
  push:
    branches: ["*"]
  workflow_dispatch:
  pull_request:

jobs:
  debug:
    name: Debug Credentials
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Check environment and secrets
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "AWS Region secret exists: ${{ secrets.AWS_REGION != '' }}"
          echo "AWS IAM Role ARN secret exists: ${{ secrets.AWS_IAM_ROLE_ARN != '' }}"
          echo "EKS Cluster Name secret exists: ${{ secrets.EKS_CLUSTER_NAME != '' }}"

      - name: Test OIDC token availability
        run: |
          if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
            echo "OIDC token request token is available"
          else
            echo "OIDC token request token is NOT available"
          fi
          if [ -n "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
            echo "OIDC token request URL is available"
          else
            echo "OIDC token request URL is NOT available"
          fi

      - name: Try original AWS_IAM_ROLE_ARN
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
        continue-on-error: true
        id: try-original

      - name: Check if original role worked
        if: steps.try-original.outcome == 'success'
        run: |
          echo "✅ Original role assumption worked!"
          aws sts get-caller-identity

      - name: Try chat-app role directly (if original failed)
        if: steps.try-original.outcome == 'failure'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::080927831740:role/chat-app
          aws-region: ${{ secrets.AWS_REGION }}
        continue-on-error: true
        id: try-chat-app

      - name: Check if chat-app role worked
        if: steps.try-chat-app.outcome == 'success'
        run: |
          echo "✅ chat-app role assumption worked!"
          aws sts get-caller-identity

      - name: Summary
        run: |
          echo "=== RESULTS ==="
          echo "Original role (${{ secrets.AWS_IAM_ROLE_ARN }}): ${{ steps.try-original.outcome }}"
          echo "chat-app role (arn:aws:iam::080927831740:role/chat-app): ${{ steps.try-chat-app.outcome }}"